apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-springboot-retryable
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-springboot-retryable
  template:
    metadata:
      labels:
        app: demo-springboot-retryable
    spec:
      containers:
        - name: demo-springboot-retryable
          image: demo-springboot-retryable:0.0.4-SNAPSHOT-99fa731
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
            - containerPort: 9990
          resources:
            requests:
              cpu: 100m
              memory: 250Mi
            limits:
              cpu: 500m
              memory: 1000Mi
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9990
            periodSeconds: 300
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9990
            periodSeconds: 30
            timeoutSeconds: 5
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 9990
            initialDelaySeconds: 60
            timeoutSeconds: 5
            failureThreshold: 5

---

apiVersion: v1
kind: Service
metadata:
  name: demo-springboot-retryable
  namespace: demo
spec:
  type: NodePort
  selector:
    app: demo-springboot-retryable
  ports:
    - name: service-port
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: management-port
      protocol: TCP
      port: 9990
      targetPort: 9990
